/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PerlinTest;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
//    @Test public void testAppHasAGreeting() {
//        CustomTerrainRenderer classUnderTest = new CustomTerrainRenderer();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
//    }
}
